#!/bin/bash

set -e

cd ${BASH_SOURCE%/*}/..

function print_help() {
  echo "Convert doc files from Markdown to EPUB format."
  echo
  echo "Usage: script/epub [options]"
  echo
  echo "Options:"
  echo "  -h, --help      Print usage"
  exit
}

function concatenate_files() {
  for file in "$@"; do
    cat $file && echo
  done
}

function markdown_to_epub() {
  pandoc -f markdown \
         --epub-chapter-level=2 \
         --epub-stylesheet=stylesheets/epub.css \
         -o docs.epub
}

function turn_references_into_internal_links() {
  echo "$1" | sed -r 's/\(.*\//(/' | sed -r 's/\((.+)\.md/(#\1/'
}

while [[ "$1" == -* ]]; do
  case $1 in
    -h | --help )   print_help
                    ;;
    * )             print_help
                    ;;
  esac
  shift
done

script/lint

files=$(find docs -type f -name "*.md")

concatenate_files $files | markdown_to_epub
